Merge working branch to master
phfdonda/new-york-times-clone pull request #2
Opened 2020-01-29 22:00 UTC by fc-anjos

This pull request merges all development, performed on aside branch, to master.
The development was implemented in the following phases, as described in the commit history:

- Adding linters config
- General Structure of HTML
- Building blocks of CSS
- Advancing on HTML and CSS
- Adding media queries
- Minor cleanup
- Adding README.md

2020-01-29 22:20 UTC, kobiyoyo commented
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

2020-01-29 22:56 UTC, kobiyoyo requested changes
## Hi Team  ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are few more things required. 

### Page structure
#### Navigation bar

- [ ]  The NY Times logo should be a link, please fix that.
- [ ] You are to use [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section .
- [ ] There are no images displayed in the **Theory of Inflation** section, please let's fix that too.
##### Original Version
![2](https://user-images.githubusercontent.com/23278161/73404893-e2094a80-42f2-11ea-993b-cbea4cc63fe0.png)

##### Your Version
![1](https://user-images.githubusercontent.com/23278161/73404849-c30ab880-42f2-11ea-8290-6b30de7ddb5e.png)

#### General
- [ ] Concerning the comments in your code: It’s better to delete commented code. If you need to review a previous version of your code, use git history

### Make changes and submit another code review request.
*Happy coding*

2020-01-30 23:44 UTC, euqueme requested changes
>### Pull Request under the review by Maria Eugenia Quemé P. (TSE)

### Hello @fc-anjos and @phfdonda  :handshake: 

### This project has great attention to detail :microscope: thank you for doing the previous changes :medal_sports: there are still some mandatory changes required to be able to give it the approval :memo: 

**Bottom part**

- [ ]  the articles at the More in space and technology and Editor's picks should be links to other articles  (you can surround them with \<a\> tags to fix them)

#### Project specific

#### Implementation details

* [ ] It uses [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the righmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

[Optional] your Live Demo doesn't seem to be working please address these [steps](https://help.github.com/en/enterprise/2.13/user/articles/configuring-a-publishing-source-for-github-pages)

I have commented your code with a suggestion where the Aside tag should be in the comments bellow :arrow_down: 

### That's it, team! :raised_hands: 
### please :pray: make the changes and submit back for a code review :rocket: 

Happy coding! :woman_technologist: 

STATUS OF THE PROJECT: REQUESTED CHANGES :vertical_traffic_light:

2020-01-30 23:44 UTC, euqueme commented on index.html
> +          <div class="aside_container">
change the **\<div\>** tag for an **\<aside\>**  tag in line #219 

> \<aside class="aside_container"\>

2020-01-31 16:07 UTC, fc-anjos commented
Thanks Maru and Adama for the reviews,

We are now committing a version that incorporates all the required changes.
As for the live-preview, we have set up the link so that it will work when the readme is merged - along all necessary files - to master branch.

2020-01-31 17:25 UTC, pelzolga123 approved these changes
Approved.

2020-01-31 17:25 UTC, pelzolga123 commented
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

2020-01-31 17:49 UTC, merged